### ISSUE TITLE
error when I executed make

### ISSUE THREAD

**Issue by JeannetteCHEN** [srsLTE/srsUE#1]
Dear developer,
      I tried to set up srsUE. So I followed the steps of the readme.

git clone https://github.com/srsLTE/srsUE.git
cd srsUE
mkdir build
cd build
cmake ../
make

It reports error when I executed "make".

/home/sdr/chenjiahua/srsUE/srsUE/ue/hdr/radio/radio_uhd.h:85:33: error: ‘cuhd_msg_handler_t’ has not been declared
       void register_msg_handler(cuhd_msg_handler_t h);
                                 ^
/home/sdr/chenjiahua/srsUE/srsUE/ue/src/radio/radio_uhd.cc:264:38: error: variable or field ‘register_msg_handler’ declared void
 void radio_uhd::register_msg_handler(cuhd_msg_handler_t h)
                                      ^
/home/sdr/chenjiahua/srsUE/srsUE/ue/src/radio/radio_uhd.cc:264:38: error: ‘cuhd_msg_handler_t’ was not declared in this scope
ue/src/radio/CMakeFiles/srsue_radio.dir/build.make:54: recipe for target 'ue/src/radio/CMakeFiles/srsue_radio.dir/radio_uhd.cc.o' failed
make[2]: *** [ue/src/radio/CMakeFiles/srsue_radio.dir/radio_uhd.cc.o] Error 1
CMakeFiles/Makefile2:292: recipe for target 'ue/src/radio/CMakeFiles/srsue_radio.dir/all' failed
make[1]: *** [ue/src/radio/CMakeFiles/srsue_radio.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

Any reply is appreciated. With my best regarding.

**Comment by suttonpd** [comment]
Hi Jeanette,
The best way to help you with this issue is on the mailing list: http://www.softwareradiosystems.com/mailman/listinfo/srslte-users
Please could you send an email to the list and include the details of the system you're building on (OS, version etc), the installed version of UHD and the cmake and make outputs for srsLTE and srsUE?

Thanks,
Paul
